Added Warn Command
YusufsDiscordbot/Yusuf-s-Moderation-Bot pull request #10
Opened 2021-11-07 20:25 UTC by RealYusufIsmail

This command will allow you to warn users if you have the right perms. You can not retrieve the warns yet.

- [ ] Does the command work
- [ ] Can anyone warn

2021-11-10 07:41 UTC, RealYusufIsmail commented
@nDZIB if you want and find a fix you can post it here or tell what to fix since I don't have access to discord at school.

2021-11-10 17:51 UTC, RealYusufIsmail commented on application/build.gradle
>      implementation group: 'me.duncte123', name: 'botCommons', version: '2.3.8'
ignore

2021-11-10 21:34 UTC, RealYusufIsmail commented
<img width="702" alt="Screenshot 2021-11-10 at 21 34 11" src="https://user-images.githubusercontent.com/67903886/141196927-d5cc6e36-6add-4970-a54d-a26eaa6d60af.png">
Command works

2021-11-10 22:33 UTC, nDZIB requested changes
This looks good. nice work

General observation
- subsequently, all SQL queries could be moved to the database module for easier debugging.
- some little refactoring can still be done to reduce some boilerplate code

2021-11-10 22:33 UTC, nDZIB commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/BanCommand.java
> +            .prepareStatement("UPDATE ban_settings SET user_id= ?, guild_id = ?, ban_reason = ?")) {
this query if it runs, will update all ban_settings stored in the database. the query could be modified to something like:
UPDATE ban_settings SET guild_id = ?, ban_reason = ? WHERE user_id = ? and the statement prepared accordingly

2021-11-10 22:33 UTC, nDZIB commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/KickCommand.java
> +                    "UPDATE kick_settings SET user_id = ?, guild_id = ?, kick_reason = ?")) {
if this query runs, will update all entries in the kick_settings table update the query to only edit ban_settings for one user  (see comment on updateBanDatabase)

2021-11-10 22:33 UTC, nDZIB commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/WarnCommand.java
> +        if (!ModerationHelper.handleHasPermissions(yusufSlashCommandEvent.getMember(),
ModerationHelper.handleHasPermissions seems to be checking only for Permission.BAN_MEMBERS 

this is not an issue if the permission to ban members is sufficient for allowing guild members to warn members

2021-11-10 22:33 UTC, nDZIB commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/WarnCommand.java
> +            logger.error("Failed to update retrieve the warn amount settings", e);
not very clear error message

2021-11-10 22:33 UTC, nDZIB commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/WarnCommand.java
> +            amountOfWarns = 0;
i think the amountOfWarns should be assigned here to 1, since it is the value that is then saved in the database. you cannot be saving a warning and saying the number of warnings is still 0

2021-11-11 06:54 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/WarnCommand.java
> +            amountOfWarns = 0;
yeah it sets it to 1 then updates it

2021-11-11 07:19 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/WarnCommand.java
> +            amountOfWarns = 0;
I see what you mean

2021-11-11 15:07 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/WarnCommand.java
> +        if (!ModerationHelper.handleHasPermissions(yusufSlashCommandEvent.getMember(),
What permissions do you recommend to use

2021-11-11 21:41 UTC, nDZIB requested changes

2021-11-11 21:41 UTC, nDZIB commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/WarnCommand.java
> +        if (!ModerationHelper.handleHasPermissions(yusufSlashCommandEvent.getMember(),
After a quick look at docs, i think the ban permission is the most suitable here

2021-11-11 21:41 UTC, nDZIB commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/BanCommand.java
> +            preparedStatement.setString(3, reason);
t1- the query can be updated to something like "UPDATE ban_settings SET ban_reason = ? WHERE user_id = ? AND guild_id = ?" so that bands of users in one server does not affect their record in other servers.

2- he order of setting the parameters of the preparedStatement should be set following the order in which they are used in the query

2021-11-11 21:41 UTC, nDZIB commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/KickCommand.java
> +            preparedStatement.setString(3, reason);
this query can be modified to something like : ""UPDATE kick_settings SET kick_reason = ? WHERE user_id = ? AND guild_id = ?" so that when user is kicked from one server it will only be registered for that server and not against all servers to which the user belongs

also order in which the parameters are set is not proper. guild_id comes first, then kick_reason and finally user_id

2021-11-11 21:41 UTC, nDZIB commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/WarnCommand.java
> +            preparedStatement.setInt(4, amountOfWarns);
don't you think this query should read: "UPDATE warn_settings SET  warn_reason = ?, amount_of_warns = ? WHERE user_id = ? AND guild_id = ?" so that only the warn_settings of a given user for a given server is updated at a time?

also if the query is modified, the the order of setting the parameters in the prepared statement should be adjusted accordingly

2021-11-13 14:37 UTC, nDZIB commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/ModerationHelper.java
> +                    "SELECT author_id FROM kick_settings WHERE user_id = ? AND guild_id = ?")) {
is the author_id ever set? selecting author_id here may return null values, given that when inserting into either ban or kick settings, no author_id is specified

2021-11-13 14:39 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/ModerationHelper.java
> +                    "SELECT author_id FROM kick_settings WHERE user_id = ? AND guild_id = ?")) {
yes it is

2021-11-13 14:43 UTC, nDZIB approved these changes

2021-11-13 14:45 UTC, merged