Improved the moderation commands.
YusufsDiscordbot/Yusuf-s-Moderation-Bot pull request #29
Opened 2021-12-16 21:33 UTC by RealYusufIsmail

Introduced a new database for the moderation commands. Kept the mute one

2021-12-16 21:38 UTC, RealYusufIsmail commented on application/build.gradle
> +    implementation group: 'io.github.yusufsdiscordbot', name: 'jda4', version: '1.0.35'
ignore

2021-12-17 09:05 UTC, Zabuzard requested changes

2021-12-17 09:05 UTC, Zabuzard commented on application/src/main/resources/database/V2__moderation.sql
> +)
This is heavily inspired by:
https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/resources/db/V5__Add_Moderation_Actions.sql

But I do not see any attribution whatsoever, this conflicts the license.

2021-12-17 09:05 UTC, Zabuzard commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/ModerationHelper.java
> +    }
This is heavily inspired by:

https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/commands/moderation/ModerationUtils.java#L331

Yet, I do not see any attribution whatsoever. This conflicts the license.

2021-12-17 12:05 UTC, RealYusufIsmail commented on application/src/main/resources/database/V2__moderation.sql
> +)
Will add later on

2021-12-17 12:06 UTC, RealYusufIsmail commented on application/src/main/java/io/github/yusufsdiscordbot/yusufsmoderationbot/slash_commands/moderation/ModerationHelper.java
> +    }
Will add

2021-12-28 16:35 UTC, RealYusufIsmail commented
Ready to be merged. can you please have a look @nDZIB

2021-12-28 16:35 UTC, RealYusufIsmail commented
Ready to be merged. can you please have a look @nDZIB

2022-01-05 15:10 UTC, RealYusufIsmail commented on application/build.gradle
>      implementation group: 'net.dv8tion', name: 'JDA', version: '4.4.0_352'
ignore

2022-01-05 19:09 UTC, merged